/**
 * Beacon runtime configuration.
 *
 * In add-on mode the HA Supervisor injects window.__BEACON_CONFIG__ via
 * runtime-config.js (generated by run.sh).  During local development the
 * values fall back to VITE_* environment variables.
 */

export interface BeaconConfig {
  ha_url: string;
  ha_token: string;
  family_name: string;
  theme: string;
  auto_dark_mode: boolean;
  weather_entity: string;
  photo_directory: string;
  photo_interval: number;
  screen_saver_timeout: number;
  addon_slug: string;
}

declare global {
  interface Window {
    __BEACON_CONFIG__?: Partial<BeaconConfig>;
  }
}

let cached: BeaconConfig | null = null;

function positiveOr(value: number | undefined, fallback: number): number {
  return typeof value === 'number' && value > 0 ? value : fallback;
}

export function getConfig(): BeaconConfig {
  if (cached) return cached;

  const runtime = window.__BEACON_CONFIG__ ?? {};

  cached = {
    ha_url: runtime.ha_url ?? import.meta.env.VITE_HA_URL ?? '',
    ha_token: runtime.ha_token || import.meta.env.VITE_HA_TOKEN || '',
    family_name: runtime.family_name || import.meta.env.VITE_FAMILY_NAME || 'My Family',
    theme: runtime.theme || import.meta.env.VITE_THEME || 'skylight',
    auto_dark_mode: runtime.auto_dark_mode ?? (import.meta.env.VITE_AUTO_DARK_MODE !== 'false'),
    weather_entity: runtime.weather_entity || import.meta.env.VITE_HA_WEATHER_ENTITY || 'weather.home',
    photo_directory: runtime.photo_directory || import.meta.env.VITE_PHOTO_DIRECTORY || '/media/beacon/photos',
    photo_interval: runtime.photo_interval ?? (Number(import.meta.env.VITE_PHOTO_INTERVAL) || 30),
    // The add-on schema allows any int; 0 or less would start the screen
    // saver within seconds of every touch, so those get the default.
    screen_saver_timeout: positiveOr(runtime.screen_saver_timeout ?? Number(import.meta.env.VITE_SCREEN_SAVER_TIMEOUT), 5),
    addon_slug: runtime.addon_slug || import.meta.env.VITE_ADDON_SLUG || '',
  };

  return cached;
}

/**
 * Override the cached config with dynamic credentials (from onboarding/OAuth).
 * Call this after the user completes setup to inject the HA URL + token
 * without requiring a page reload.
 */
export function patchConfig(patch: Partial<BeaconConfig>): void {
  const current = getConfig();
  cached = { ...current, ...patch };
}
