/**
 * Beacon runtime configuration.
 *
 * In add-on mode the HA Supervisor injects window.__BEACON_CONFIG__ via
 * runtime-config.js (generated by run.sh). Non-secret display preferences
 * can fall back to VITE_* values; HA credentials never come from a build.
 */

export interface BeaconConfig {
  ha_url: string;
  ha_token: string;
  ha_available: boolean;
  theme: string;
  auto_dark_mode: boolean;
  weather_entity: string;
  photo_directory: string;
  photo_interval: number;
  screen_saver_timeout: number;
  addon_slug: string;
}

declare global {
  interface Window {
    __BEACON_CONFIG__?: Partial<BeaconConfig>;
  }
}

let cached: BeaconConfig | null = null;

function positiveOr(value: number | undefined, fallback: number): number {
  return typeof value === 'number' && value > 0 ? value : fallback;
}

export function getConfig(): BeaconConfig {
  if (cached) return cached;

  const runtime = window.__BEACON_CONFIG__ ?? {};

  cached = {
    ha_url: runtime.ha_url ?? import.meta.env.VITE_HA_URL ?? '',
    ha_token: '',
    ha_available: runtime.ha_available ?? true,
    theme: runtime.theme || import.meta.env.VITE_THEME || 'skylight',
    auto_dark_mode: runtime.auto_dark_mode ?? (import.meta.env.VITE_AUTO_DARK_MODE !== 'false'),
    weather_entity: runtime.weather_entity || import.meta.env.VITE_HA_WEATHER_ENTITY || 'weather.home',
    photo_directory: runtime.photo_directory || import.meta.env.VITE_PHOTO_DIRECTORY || '/media/beacon/photos',
    // The add-on schema allows any int; 0 or less would change photos every
    // few milliseconds, or start the screen saver within seconds of every
    // touch, so those get the default.
    photo_interval: positiveOr(runtime.photo_interval ?? Number(import.meta.env.VITE_PHOTO_INTERVAL), 30),
    screen_saver_timeout: positiveOr(runtime.screen_saver_timeout ?? Number(import.meta.env.VITE_SCREEN_SAVER_TIMEOUT), 5),
    addon_slug: runtime.addon_slug || import.meta.env.VITE_ADDON_SLUG || '',
  };

  return cached;
}

/**
 * Override config values, e.g. with the Home Assistant login saved by
 * onboarding (see applySavedLogin). Changes the cached object in place, so
 * modules that read the config once when loaded (App) see the change too.
 */
export function patchConfig(patch: Partial<BeaconConfig>): void {
  Object.assign(getConfig(), patch);
}
